server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
    http:
      encoding:
        force: true
        charset: utf-8
        enabled: true
#日志
logging:
  level:
    com.heiya123.music: debug
qmkg:
  userAttr:
    619f94812d2e328e32:
      id: 619f94812d2e328e32
      singer: 赖琼芳
    63999887222f3f8235:
      id: 63999887222f3f8235
      singer: 赖琼芳
    659c9f85222935883d:
      id: 659c9f85222935883d
      singer: 谭礼珠
