server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
    http:
      encoding:
        force: true
        charset: utf-8
        enabled: true
#日志
logging:
  level:
    com.heiya123.music: debug